version: '3'

tasks:
  build:
    cmds:
      - odin build src/client -out:bin/client -o:none -debug
    sources:
      - ./src/client/**/*.odin
      - ./src/reader/**/*.odin
      - ./src/domain/**/*.odin
    generates:
      - bin/client
    silent: true

  run:
    cmds:
      - bin/client
    deps:
      - build
    silent: true

  test:
    cmds:
      - task: test-client
      - task: test-domain
        
    
  test-client:
    cmds:
      - odin test src/client -out:bin/client
    sources:
      - ./src/client/**/*.odin
  
  test-domain:
    cmds:
      - odin test src/domain -out:bin/domain
    sources:
      - ./src/domain/**/*.odin

interval: 250ms