version: '3'

tasks:
  build:
    cmds:
      - odin build src/ -out:target/client -o:none -debug
    sources:
      - ./src/**/*.odin
    generates:
      - target/client
    silent: true

  run:
    cmds:
      - target/client
    deps:
      - build
    silent: true

  # test:
  #   cmds:
  #     - task: test-client
        
  # test-client:
  #   cmds:
  #     - odin test src/client -out:bin/client
  #   sources:
  #     - ./src/client/**/*.odin
  

interval: 250ms